DISTRICT_TO_LAU1 = {
    "Bratislava I": 101,
    "Bratislava II": 102,
    "Bratislava III": 103,
    "Bratislava IV": 104,
    "Bratislava V": 105,
    "Malacky": 106,
    "Pezinok": 107,
    "Senec": 108,
    "Dunajská Streda": 201,
    "Galanta": 202,
    "Hlohovec": 203,
    "Piešťany": 204,
    "Senica": 205,
    "Skalica": 206,
    "Trnava": 207,
    "Bánovce nad Bebravou": 301,
    "Ilava": 302,
    "Myjava": 303,
    "Nové Mesto nad Váhom": 304,
    "Partizánske": 305,
    "Považská Bystrica": 306,
    "Prievidza": 307,
    "Púchov": 308,
    "Trenčín": 309,
    "Komárno": 401,
    "Levice": 402,
    "Nitra": 403,
    "Nové Zámky": 404,
    "Šaľa": 405,
    "Topoľčany": 406,
    "Zlaté Moravce": 407,
    "Bytča": 501,
    "Čadca": 502,
    "Dolný Kubín": 503,
    "Kysucké Nové Mesto": 504,
    "Liptovský Mikuláš": 505,
    "Martin": 506,
    "Námestovo": 507,
    "Ružomberok": 508,
    "Turčianske Teplice": 509,
    "Tvrdošín": 510,
    "Žilina": 511,
    "Banská Bystrica": 601,
    "Banská Štiavnica": 602,
    "Brezno": 603,
    "Detva": 604,
    "Krupina": 605,
    "Lučenec": 606,
    "Poltár": 607,
    "Revúca": 608,
    "Rimavská Sobota": 609,
    "Veľký Krtíš": 610,
    "Zvolen": 611,
    "Žarnovica": 612,
    "Žiar nad Hronom": 613,
    "Bardejov": 701,
    "Humenné": 702,
    "Kežmarok": 703,
    "Levoča": 704,
    "Medzilaborce": 705,
    "Poprad": 706,
    "Prešov": 707,
    "Sabinov": 708,
    "Snina": 709,
    "Stará Ľubovňa": 710,
    "Stropkov": 711,
    "Svidník": 712,
    "Vranov nad Topľou": 713,
    "Gelnica": 801,
    "Košice I": 802,
    "Košice II": 803,
    "Košice III": 804,
    "Košice IV": 805,
    "Košice - okolie": 806,
    "Michalovce": 807,
    "Rožňava": 808,
    "Sobrance": 809,
    "Spišská Nová Ves": 810,
    "Trebišov": 811,
    "Cudzina": 900,
}

UNIVERSAL_PARTY_NAMES = {
    # SMER - sociálna demokracia
    "SMER": "SMER-SD",
    "SMER (tretia cesta)": "SMER-SD",
    "SMER - SD": "SMER-SD",
    "SMER-SD": "SMER-SD",
    "SMER - sociálna demokracia": "SMER-SD",
    # SDKÚ-DS
    "SDKÚ": "SDKÚ-DS",
    "SDKÚ - DS": "SDKÚ-DS",
    "SDKÚ- DS": "SDKÚ-DS",
    "SDKÚ-DS": "SDKÚ-DS",
    "Slovenská demokratická a kresťanská únia - Demokratická strana": "SDKÚ-DS",
    "SDKÚ - DS - Slovenská demokratická a kresťanská únia - Demokratická strana": "SDKÚ-DS",
    # OĽaNO / Slovensko
    "OĽaNO": "OĽaNO / SLOVENSKO",
    "Obyčajní ľudia": "OĽaNO / SLOVENSKO",
    "OBYČAJNÍ ĽUDIA a nezávislé osobnosti": "OĽaNO / SLOVENSKO",
    "OBYČAJNÍ ĽUDIA a nezávislé osobnosti (OĽANO - NOVA)": "OĽaNO / SLOVENSKO",
    "OBYČAJNÍ ĽUDIA a nezávislé osobnosti (OĽANO)": "OĽaNO / SLOVENSKO",
    "OBYČAJNÍ ĽUDIA a nezávislé osobnosti (OĽANO), NOVA, Kresťanská únia (KÚ), ZMENA ZDOLA": "OĽaNO / SLOVENSKO",
    "OĽANO A PRIATELIA: OBYČAJNÍ ĽUDIA (OĽANO), NEZÁVISLÍ KANDIDÁTI (NEKA), NOVA, SLOBODNÍ A ZODPOVEDNÍ, PAČIVALE ROMA, MAGYAR SZÍVEK a Kresťanská únia a ZA ĽUDÍ": "OĽaNO / SLOVENSKO",
    "SLOVENSKO, ZA ĽUDÍ": "OĽaNO / SLOVENSKO",
    # Sloboda a Solidarita (SaS)
    "SaS": "SaS",
    "Sloboda a Solidarita": "SaS",
    # Hlas - sociálna demokracia
    "HLAS - sociálna demokracia": "Hlas-SD",
    # Progresívne Slovensko (PS)
    "PS": "Progresívne Slovensko",
    "Koalícia Progresívne Slovensko a SPOLU - občianska demokracia": "Progresívne Slovensko",
    "Progresívne Slovensko": "Progresívne Slovensko",
    # Kresťanskodemokratické hnutie (KDH)
    "KDH": "KDH",
    "Kresťanskodemokratické hnutie": "KDH",
    # Slovenská národná strana (SNS)
    "SNS": "SNS",
    "SNS, P SNS": "SNS",
    "Slovenská národná strana": "SNS",
    # ĽS-HZDS
    "HZDS": "ĽS-HZDS",
    "ĽS - HZDS": "ĽS-HZDS",
    "ĽS-HZDS": "ĽS-HZDS",
    # SMK / Aliancia (Hungarian minority parties)
    "SMK-MKP": "SMK / Aliancia",
    "SMK - MKP": "SMK / Aliancia",
    "Strana maďarskej komunity - Magyar Közösség Pártja": "SMK / Aliancia",
    "Magyar Közösségi Összefogás - Maďarská komunitná spolupatričnosť": "SMK / Aliancia",
    "SZÖVETSÉG - Magyarok. Nemzetiségek. Regiók. | ALIANCIA - Maďari. Národnosti. Regióny": "SMK / Aliancia",
    "Magyar Szövetség - Maďarská aliancia": "SMK / Aliancia",
    # Most-Híd
    "MOST - HÍD": "Most-Híd",
    "Modrí, Most - Híd": "Most-Híd",
    # Kotleba / ĽSNS
    "ĽSNS": "ĽSNS - Kotlebovci",
    "ĽS Naše Slovensko": "ĽSNS - Kotlebovci",
    "Ľudová strana Naše Slovensko": "ĽSNS - Kotlebovci",
    "Kotleba - Ľudová strana Naše Slovensko": "ĽSNS - Kotlebovci",
    "Kotlebovci - Ľudová strana Naše Slovensko": "ĽSNS - Kotlebovci",
    # Sme Rodina
    "SME RODINA - Boris Kollár": "Sme Rodina",
    "SME RODINA": "Sme Rodina",
    # Republika
    "REPUBLIKA": "Republika",
    # Komunistická strana Slovenska (KSS)
    "KSS": "KSS",
    "Komunistická strana Slovenska": "KSS",
    "Koalícia Komunistická strana Slovenska, VZDOR - strana práce": "KSS",
    # Strana zelených (SZ / SZS)
    "SZ": "Strana zelených",
    "SZS": "Strana zelených",
    "Zelení": "Strana zelených",
    "Strana zelených": "Strana zelených",
    "Strana zelených Slovenska": "Strana zelených",
    # Slovenská ľudová strana (SĽS)
    "SĽS": "SĽS - Andreja Hlinku",
    "Slovenská ľudová strana": "SĽS - Andreja Hlinku",
    "Slovenská ľudová strana Andreja Hlinku": "SĽS - Andreja Hlinku",
    # Demokratická strana (DS)
    "DS": "Demokratická strana",
    "DS - Ľudo Kaník": "Demokratická strana",
    "Demokratická strana": "Demokratická strana",
    # Občianska konzervatívna strana (OKS)
    "OKS": "OKS",
    "Občianska konzervatívna strana": "OKS",
    # Vlasť / Vlastenecký blok
    "VLASŤ": "Vlasť",
    "Vlastenecký blok": "Vlastenecký blok",
    # HZD
    "HZD": "HZD",
    "HZD, ĽÚ": "HZD",
    # VZDOR
    "VZDOR": "VZDOR",
    "VZDOR - strana práce": "VZDOR",
    # TIP
    "TIP": "Strana TIP",
    "Strana TIP": "Strana TIP",
    # 99%
    "99%": "99 % - občiansky hlas",
    "99 % - občiansky hlas": "99 % - občiansky hlas",
    # Priama Demokracia
    "PD": "PRIAMA DEMOKRACIA",
    "PRIAMA DEMOKRACIA": "PRIAMA DEMOKRACIA",
    "PRIAMA DEMOKRACIA, Kresťanská ľudová strana": "PRIAMA DEMOKRACIA",
}
